export function ToDoItem(props) {
  return props.items.map((item, index) => (
    <li
      key={item.id}
      onClick={() => {
        props.onChecked(item.id, index);
      }}
    >
      {item.name}
    </li>
  ));
}

//need a way of sending an id generated by something else back and forth because the index is not a good id, in fact it might be the worst.
